import {
  ClinicSettings,
  Appointment,
  Patient,
  MessageThread,
  Specialization,
  Treatment,
  TechItem,
  Testimonial,
  GalleryItem,
  FAQItem,
  AdminUser,
} from "../types";

export const DEMO_ADMIN_USER: AdminUser = {
  id: "usr-admin-01",
  email: "admin@doctorclinic.com",
  name: "Dr. Evelyn Reed",
  role: "Medical Director",
  avatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80",
  department: "Cardiology & Operations",
};

export const CLINIC_INFO = {
  name: "AuraHealth Medical & Surgical Center",
  tagline: "Advanced Medical Care with Human Touch",
  phone: "+1 (800) 555-0199",
  emergencyPhone: "+1 (800) 911-AURA",
  email: "care@aurahealthclinic.com",
  whatsappNumber: "+18005550199",
  address: "742 Evergreen Medical Blvd, Suite 400, New York, NY 10021",
  hours: [
    { days: "Monday - Friday", time: "8:00 AM - 8:00 PM" },
    { days: "Saturday", time: "9:00 AM - 5:00 PM" },
    { days: "Sunday", time: "Emergency & Priority Appointments Only" },
  ],
  doctor: {
    name: "Dr. Evelyn Reed, M.D., FACC",
    title: "Chief Medical Officer & Senior Consultant Physician",
    qualifications: "MD (Harvard Medical School), FACC, Board Certified in Internal Medicine & Cardiovascular Disease",
    experienceYears: 22,
    surgeriesCount: 4500,
    patientsTreated: "25,000+",
    bio: "Dr. Evelyn Reed is a world-renowned physician with over two decades of clinical leadership in preventive medicine, interventional cardiology, and complex chronic care management. Having completed her residency at Massachusetts General Hospital and fellowship at Johns Hopkins Medical Institute, Dr. Reed combines cutting-edge diagnostic precision with a deeply empathetic, patient-first approach.",
    philosophy: "We believe medicine is not just about managing symptoms—it is about restoring vitality, empowering patients with knowledge, and utilizing state-of-the-art non-invasive technology for lasting longevity.",
    degrees: [
      { title: "Doctor of Medicine (M.D.)", institution: "Harvard Medical School, Magna Cum Laude", year: "2002" },
      { title: "Residency in Internal Medicine", institution: "Massachusetts General Hospital", year: "2002 - 2005" },
      { title: "Fellowship in Cardiovascular Medicine", institution: "Johns Hopkins University Hospital", year: "2005 - 2008" },
      { title: "Fellow of American College of Cardiology (FACC)", institution: "American College of Cardiology", year: "2010" },
    ],
    awards: [
      "Top Physician in New York (2020 - 2025)",
      "Excellence in Clinical Innovation Award - AMA",
      "Pioneer in Non-Invasive Vascular Diagnostics",
      "Author of 40+ Peer-Reviewed Medical Publications",
    ],
  },
};

export const INITIAL_CLINIC_SETTINGS: ClinicSettings = {
  clinicName: "AuraHealth Medical & Surgical Center",
  doctorName: "Dr. Evelyn Reed, M.D., FACC",
  qualification: "MD (Harvard Medical School), Board Certified FACC",
  specialization: "Cardiology & Internal Medicine",
  experienceYears: 22,
  avatarUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
  coverImageUrl: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=1000&auto=format&fit=crop&q=80",
  logoUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80",

  address: "742 Evergreen Medical Blvd, Suite 400, New York, NY 10021",
  googleMapsUrl: "https://maps.google.com/?q=New+York+NY",
  phone: "+1 (800) 555-0199",
  emergencyPhone: "+1 (800) 911-AURA",
  email: "care@aurahealthclinic.com",
  website: "https://admin.doctorclinic.com",
  whatsappNumber: "+18005550199",

  consultationFee: 150,
  slotDurationMinutes: 30,
  bufferTimeMinutes: 10,
  maxBookingsPerDay: 30,
  workingHours: [
    { day: "Monday", isOpen: true, openTime: "08:00 AM", closeTime: "08:00 PM" },
    { day: "Tuesday", isOpen: true, openTime: "08:00 AM", closeTime: "08:00 PM" },
    { day: "Wednesday", isOpen: true, openTime: "08:00 AM", closeTime: "08:00 PM" },
    { day: "Thursday", isOpen: true, openTime: "08:00 AM", closeTime: "08:00 PM" },
    { day: "Friday", isOpen: true, openTime: "08:00 AM", closeTime: "08:00 PM" },
    { day: "Saturday", isOpen: true, openTime: "09:00 AM", closeTime: "05:00 PM" },
    { day: "Sunday", isOpen: false, openTime: "Closed", closeTime: "Closed" },
  ],
  lunchBreak: { start: "01:00 PM", end: "02:00 PM" },
  slotIntervalMinutes: 30,
  autoApproval: false,

  weeklyOff: "Sunday",
  publicHolidays: [
    { id: "h-1", name: "Labor Day", date: "2026-09-07" },
    { id: "h-2", name: "Thanksgiving Day", date: "2026-11-26" },
    { id: "h-3", name: "Christmas Day", date: "2026-12-25" },
  ],
  vacationStart: "",
  vacationEnd: "",
  emergencyClosure: false,
  emergencyMessage: "The clinic is temporarily closed for emergency maintenance. For urgent medical emergencies, call 911.",

  emailNotifications: true,
  whatsappNotifications: true,
  reminder24h: true,
  reminder2h: true,

  primaryColor: "#14b8a6",
  secondaryColor: "#0f172a",
  faviconUrl: "/favicon.ico",

  twoFactorEnabled: false,
  activeSessions: [
    { id: "s-1", device: "Chrome / Windows 11 (This Device)", ip: "192.168.1.42", location: "New York, USA", lastActive: "Active Now", isCurrent: true },
    { id: "s-2", device: "Safari / iPhone 15 Pro", ip: "172.56.21.90", location: "New York, USA", lastActive: "2 hours ago", isCurrent: false },
  ],
};

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: "APT-1001",
    patientId: "PAT-801",
    patientName: "Sarah Jenkins",
    patientPhone: "+1 (555) 234-5678",
    patientEmail: "sarah.j@example.com",
    patientAge: 34,
    patientGender: "Female",
    doctorName: "Dr. Alexander Vance",
    department: "Cardiology",
    date: "2026-07-31",
    time: "09:00 AM",
    type: "In-Person",
    status: "In Progress",
    reason: "Routine Cardiac Follow-up & ECG Check",
    notes: "Patient reports mild chest tightness after exercise. BP: 125/82 mmHg.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "APT-1002",
    patientId: "PAT-802",
    patientName: "Marcus Sterling",
    patientPhone: "+1 (555) 345-6789",
    patientEmail: "m.sterling@example.com",
    patientAge: 48,
    patientGender: "Male",
    doctorName: "Dr. Elena Rostova",
    department: "Neurology",
    date: "2026-07-31",
    time: "09:45 AM",
    type: "Telehealth",
    status: "Waiting",
    reason: "Migraine Medication Review",
    notes: "Pre-session questionnaire submitted. Experiencing aura twice weekly.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "APT-1003",
    patientId: "PAT-803",
    patientName: "Elena Rodriguez",
    patientPhone: "+1 (555) 456-7890",
    patientEmail: "elena.r@example.com",
    patientAge: 29,
    patientGender: "Female",
    doctorName: "Dr. Alexander Vance",
    department: "Cardiology",
    date: "2026-07-31",
    time: "10:30 AM",
    type: "In-Person",
    status: "Scheduled",
    reason: "Palpitations & Stress Consultation",
    notes: "First time consultation. Medical history requested.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "APT-1004",
    patientId: "PAT-804",
    patientName: "Robert Chen",
    patientPhone: "+1 (555) 567-8901",
    patientEmail: "robert.chen@example.com",
    patientAge: 62,
    patientGender: "Male",
    doctorName: "Dr. Julian Thorne",
    department: "Orthopedics",
    date: "2026-07-31",
    time: "11:15 AM",
    type: "In-Person",
    status: "Scheduled",
    reason: "Post-op Knee Arthroscopy Check",
    notes: "X-ray results uploaded to chart.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "APT-1005",
    patientId: "PAT-805",
    patientName: "Amanda White",
    patientPhone: "+1 (555) 678-9012",
    patientEmail: "amanda.w@example.com",
    patientAge: 41,
    patientGender: "Female",
    doctorName: "Dr. Sophia Patel",
    department: "Dermatology",
    date: "2026-07-31",
    time: "02:00 PM",
    type: "Follow-up",
    status: "Scheduled",
    reason: "Skin Lesion Pathology Results",
    notes: "Biopsy report ready for review.",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "APT-1006",
    patientId: "PAT-806",
    patientName: "David Miller",
    patientPhone: "+1 (555) 789-0123",
    patientEmail: "david.m@example.com",
    patientAge: 55,
    patientGender: "Male",
    doctorName: "Dr. Alexander Vance",
    department: "Cardiology",
    date: "2026-07-31",
    time: "08:15 AM",
    type: "In-Person",
    status: "Completed",
    reason: "Hypertension Control Visit",
    notes: "BP stabilized at 118/76 mmHg. Refilled Lisinopril 10mg.",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "APT-1007",
    patientId: "PAT-807",
    patientName: "Chloe Bennett",
    patientPhone: "+1 (555) 890-1234",
    patientEmail: "chloe.b@example.com",
    patientAge: 26,
    patientGender: "Female",
    doctorName: "Dr. Elena Rostova",
    department: "Neurology",
    date: "2026-08-01",
    time: "10:00 AM",
    type: "Telehealth",
    status: "Scheduled",
    reason: "Sleep Study Assessment",
    notes: "Polysomnography results attached.",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: "PAT-801",
    mrn: "MRN-90821",
    name: "Sarah Jenkins",
    age: 34,
    gender: "Female",
    phone: "+1 (555) 234-5678",
    email: "sarah.j@example.com",
    bloodGroup: "A+",
    address: "742 Evergreen Terrace, Springfield",
    lastVisit: "2026-07-31",
    nextAppointment: "2026-08-14 (Cardiology)",
    totalVisits: 8,
    status: "Active",
    allergies: ["Penicillin", "Peanuts"],
    medications: ["Atorvastatin 20mg", "Metoprolol 25mg"],
    conditions: ["Hypertension", "Mild Arrhythmia"],
    notes: "Patient is compliant with medication schedule. High adherence.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "PAT-802",
    mrn: "MRN-90822",
    name: "Marcus Sterling",
    age: 48,
    gender: "Male",
    phone: "+1 (555) 345-6789",
    email: "m.sterling@example.com",
    bloodGroup: "O+",
    address: "128 Baker Street, Suite 400",
    lastVisit: "2026-07-31",
    nextAppointment: "Today 09:45 AM (Neurology)",
    totalVisits: 14,
    status: "Follow-up Required",
    allergies: ["Sulfa Drugs"],
    medications: ["Sumatriptan 50mg", "Magnesium Glycinate 400mg"],
    conditions: ["Chronic Migraine", "Insomnia"],
    notes: "Requested MRI brain scan update. Monitor headache logs.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "PAT-803",
    mrn: "MRN-90823",
    name: "Elena Rodriguez",
    age: 29,
    gender: "Female",
    phone: "+1 (555) 456-7890",
    email: "elena.r@example.com",
    bloodGroup: "B-",
    address: "405 Ocean Drive, Apt 12B",
    lastVisit: "2026-05-12",
    nextAppointment: "Today 10:30 AM (Cardiology)",
    totalVisits: 3,
    status: "Active",
    allergies: ["None Reported"],
    medications: ["Multivitamins"],
    conditions: ["Sinus Tachycardia"],
    notes: "New patient referral from Dr. Hernandez.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "PAT-804",
    mrn: "MRN-90824",
    name: "Robert Chen",
    age: 62,
    gender: "Male",
    phone: "+1 (555) 567-8901",
    email: "robert.chen@example.com",
    bloodGroup: "AB+",
    address: "89 Pinecrest Blvd, Sector 7",
    lastVisit: "2026-07-20",
    nextAppointment: "Today 11:15 AM (Orthopedics)",
    totalVisits: 22,
    status: "Active",
    allergies: ["NSAIDs", "Aspirin"],
    medications: ["Glucosamine 1500mg", "Acetaminophen 500mg"],
    conditions: ["Osteoarthritis Left Knee", "Post-Arthroscopy"],
    notes: "Physical therapy progressing well. Range of motion improved to 110 degrees.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "PAT-805",
    mrn: "MRN-90825",
    name: "Amanda White",
    age: 41,
    gender: "Female",
    phone: "+1 (555) 678-9012",
    email: "amanda.w@example.com",
    bloodGroup: "O-",
    address: "312 Sunset Blvd, Westside",
    lastVisit: "2026-07-25",
    nextAppointment: "Today 02:00 PM (Dermatology)",
    totalVisits: 6,
    status: "Follow-up Required",
    allergies: ["Latex"],
    medications: ["Topical Hydrocortisone 1%"],
    conditions: ["Atypical Nevus", "Eczema"],
    notes: "Punch biopsy performed on right shoulder lesion.",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "PAT-806",
    mrn: "MRN-90826",
    name: "David Miller",
    age: 55,
    gender: "Male",
    phone: "+1 (555) 789-0123",
    email: "david.m@example.com",
    bloodGroup: "A-",
    address: "512 Oakwood Lane",
    lastVisit: "2026-07-31",
    totalVisits: 19,
    status: "Active",
    allergies: ["Codeine"],
    medications: ["Lisinopril 10mg", "Metformin 500mg"],
    conditions: ["Type 2 Diabetes", "Essential Hypertension"],
    notes: "HbA1c last recorded at 6.4%. Excellent glycemic control.",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
  },
];

export const INITIAL_MESSAGES: MessageThread[] = [
  {
    id: "MSG-301",
    patientId: "PAT-801",
    patientName: "Sarah Jenkins",
    patientAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    lastMessage: "Doctor, I took my morning dose as instructed. Should I log the BP reading now?",
    timestamp: "10:14 AM",
    unreadCount: 1,
    category: "Appointment Inquiry",
    isUrgent: false,
    messages: [
      { id: "m-1", sender: "doctor", text: "Hello Sarah, please make sure to measure your blood pressure after 15 minutes of rest.", timestamp: "09:30 AM" },
      { id: "m-2", sender: "patient", text: "Doctor, I took my morning dose as instructed. Should I log the BP reading now?", timestamp: "10:14 AM" },
    ],
  },
  {
    id: "MSG-302",
    patientId: "PAT-802",
    patientName: "Marcus Sterling",
    patientAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    lastMessage: "URGENT: Experiencing intense migraine aura ahead of our 09:45 AM video call.",
    timestamp: "09:12 AM",
    unreadCount: 2,
    category: "Telehealth",
    isUrgent: true,
    messages: [
      { id: "m-3", sender: "patient", text: "Hi Dr. Elena, the aura started about 20 minutes ago.", timestamp: "09:05 AM" },
      { id: "m-4", sender: "patient", text: "URGENT: Experiencing intense migraine aura ahead of our 09:45 AM video call.", timestamp: "09:12 AM" },
    ],
  },
  {
    id: "MSG-303",
    patientId: "PAT-805",
    patientName: "Amanda White",
    patientAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    lastMessage: "Could you confirm if the biopsy lab results have arrived before my 2 PM visit?",
    timestamp: "Yesterday",
    unreadCount: 0,
    category: "Lab Result",
    isUrgent: false,
    messages: [
      { id: "m-5", sender: "patient", text: "Could you confirm if the biopsy lab results have arrived before my 2 PM visit?", timestamp: "Yesterday 04:30 PM" },
      { id: "m-6", sender: "doctor", text: "Yes Amanda! The pathology report came in this morning and looks clear. We will discuss details at 2 PM.", timestamp: "Yesterday 05:10 PM" },
    ],
  },
];

export const SPECIALIZATIONS: Specialization[] = [
  {
    id: "cardiology",
    title: "Comprehensive Cardiology",
    iconName: "HeartPulse",
    shortDesc: "Advanced preventive heart care, arrhythmia management, and non-invasive cardiac evaluation.",
    fullDesc: "Our Cardiology department offers 360-degree cardiovascular diagnostics including 3D Echocardiography, Holter Monitoring, TMT stress evaluation, and personalized preventive therapy to reduce cardiac risks.",
    conditions: ["Hypertension", "Coronary Artery Disease", "Arrhythmias", "Heart Failure Risk", "High Cholesterol"],
    features: ["24/7 Holter & ECG Analysis", "Advanced Lipid Profiling", "Zero-Radiation Ultrasound Cardiology"],
    gradient: "from-rose-500 to-red-600",
  },
  {
    id: "internal-medicine",
    title: "Advanced Internal Medicine",
    iconName: "Stethoscope",
    shortDesc: "Expert diagnosis and long-term management of complex metabolic & systemic health conditions.",
    fullDesc: "We provide comprehensive health audits for adults, treating chronic conditions, metabolic disorders, and auto-immune issues with evidence-based medical protocols.",
    conditions: ["Type 2 Diabetes", "Thyroid Disorders", "Metabolic Syndrome", "Hypertension", "Autoimmune Conditions"],
    features: ["Continuous Glucose Monitoring", "Personalized Reversal Plans", "Multi-system Diagnostic Audits"],
    gradient: "from-sky-500 to-blue-600",
  },
  {
    id: "preventive-wellness",
    title: "Preventive Care & Executive Health",
    iconName: "ShieldCheck",
    shortDesc: "Tailored executive health screening packages designed for early disease detection and longevity.",
    fullDesc: "Proactive healthcare is key to longevity. Our executive health screenings utilize advanced bio-marker panels and AI-assisted imaging to catch micro-abnormalities before symptoms arise.",
    conditions: ["Early Organ Stress", "Nutritional Deficiencies", "Cardiovascular Risk Factors", "Hormonal Imbalance"],
    features: ["Full-body High-resolution Scan", "Biomarker Longevity Panel", "Same-Day Comprehensive Report"],
    gradient: "from-emerald-500 to-teal-600",
  },
  {
    id: "endocrinology",
    title: "Endocrinology & Thyroid Care",
    iconName: "Activity",
    shortDesc: "Specialized endocrine management for thyroid, adrenal, pituitary, and hormone disorders.",
    fullDesc: "Precision endocrine diagnostics focusing on thyroid nodules, PCOS, hormonal imbalances, and osteoporosis through tailored endocrine therapies.",
    conditions: ["Hypothyroidism & Hashimoto's", "Thyroid Nodules", "PCOS / Hormone Imbalance", "Osteoporosis"],
    features: ["In-house Thyroid Ultrasound", "Hormone Optimization Therapy", "Bone Mineral Density Audits"],
    gradient: "from-indigo-500 to-purple-600",
  },
  {
    id: "vascular-health",
    title: "Vascular & Circulation Medicine",
    iconName: "Zap",
    shortDesc: "Non-invasive vascular doppler, peripheral artery disease care, and venous circulation management.",
    fullDesc: "Diagnosing peripheral vascular diseases, varicose venous insufficiency, and arterial circulation issues using high-frequency Doppler ultrasound.",
    conditions: ["Peripheral Artery Disease", "Varicose Vein Symptoms", "Deep Vein Thrombosis (DVT) Risk", "Diabetic Foot Circulation"],
    features: ["Duplex Doppler Scan", "Non-Surgical Venous Therapy", "Micro-vascular Circulation Care"],
    gradient: "from-cyan-500 to-blue-700",
  },
  {
    id: "geriatric-care",
    title: "Senior & Geriatric Care",
    iconName: "Users",
    shortDesc: "Compassionate, holistic medical care tailored specifically for aging adults and complex care.",
    fullDesc: "Focusing on preserving mobility, cognitive clarity, polypharmacy management, and fall prevention for senior patients in a warm, welcoming environment.",
    conditions: ["Polypharmacy Management", "Frailty & Joint Health", "Memory & Cognitive Decline", "Hypertension & Diabetes"],
    features: ["Home Visit Coordination", "Medication Simplification", "Dedicated Senior Support Specialist"],
    gradient: "from-amber-500 to-orange-600",
  },
];

export const TREATMENTS: Treatment[] = [
  {
    id: "tr-1",
    name: "Advanced 3D Echocardiography & Cardiac Strain Analysis",
    category: "Cardiology",
    description: "High-resolution ultrasound imaging providing live 3D visualization of heart valves, wall motion, and strain velocity.",
    duration: "45 Minutes",
    recoveryTime: "Immediate (Non-Invasive)",
    keyBenefits: ["Zero Radiation", "Instant Live Results", "Detects Early Valve Strain"],
    isPopular: true,
  },
  {
    id: "tr-2",
    name: "Comprehensive Executive Longevity & Health Audit",
    category: "Preventive Health",
    description: "Full-body metabolic, cardiovascular, genetic, and imaging evaluation designed to pinpoint early health risks.",
    duration: "2 - 3 Hours",
    recoveryTime: "Immediate",
    keyBenefits: ["120+ Biomarkers Analyzed", "Personalized Longevity Roadmap", "Physician One-on-One Review"],
    isPopular: true,
  },
  {
    id: "tr-3",
    name: "24-Hour Ambulatory Blood Pressure & Holter ECG",
    category: "Cardiology",
    description: "Continuous 24 to 72 hour monitoring of cardiac rhythm and blood pressure dynamics during daily activity.",
    duration: "Fitting: 15 Mins",
    recoveryTime: "Immediate",
    keyBenefits: ["Silent Arrhythmia Detection", "Masked Hypertension Assessment", "Comfortable Wearable Tech"],
  },
  {
    id: "tr-4",
    name: "Intensive Diabetes Reversal & Remission Protocol",
    category: "Internal Medicine",
    description: "Structured multi-month medical and nutritional intervention aimed at lowering HbA1c and reducing insulin dependency.",
    duration: "3 - 6 Months Care Plan",
    recoveryTime: "Progressive",
    keyBenefits: ["Continuous Glucose Monitor (CGM)", "Direct Physician Access", "Targeted Dietary Science"],
    isPopular: true,
  },
  {
    id: "tr-5",
    name: "Carotid & Peripheral Vascular Doppler Scan",
    category: "Vascular Medicine",
    description: "Ultrasonic evaluation of carotid blood flow to assess stroke risk and blood vessel stiffness.",
    duration: "30 Minutes",
    recoveryTime: "Immediate",
    keyBenefits: ["Early Stroke Prevention", "Plaque Quantification", "Non-Invasive & Painless"],
  },
  {
    id: "tr-6",
    name: "Thyroid Fine-Needle Aspiration & Ultrasound",
    category: "Endocrinology",
    description: "Precision ultrasound-guided evaluation and minimal biopsy of thyroid nodules for instant pathology review.",
    duration: "30 Minutes",
    recoveryTime: "Same-day normal activity",
    keyBenefits: ["High Precision Guidance", "In-office Rapid Cytology", "Minimal Discomfort"],
  },
];

export const TECHNOLOGIES: TechItem[] = [
  {
    id: "tech-1",
    name: "Epiq 7G 3D Color Doppler Ultrasound",
    category: "Diagnostic Imaging",
    description: "Next-generation ultrasound architecture producing ultra-clear micro-vascular anatomical detail and cardiac strain mapping.",
    highlight: "Sub-millimeter resolution for heart valves & vascular walls",
    specs: ["nSIGHT Imaging Architecture", "PureWave Transducer Technology", "AI Auto-Strain Calculation"],
    icon: "Activity",
  },
  {
    id: "tech-2",
    name: "Continuous Ambulatory Rhythm Monitoring System",
    category: "Wearable Diagnostics",
    description: "Lightweight, water-resistant patch sensor recording multi-lead ECG continuously for up to 14 consecutive days.",
    highlight: "100% wireless data sync with cloud diagnostic engine",
    specs: ["Continuous 14-day record", "Automatic Spike AI Detection", "Zero Patient Daily Hassle"],
    icon: "Wifi",
  },
  {
    id: "tech-3",
    name: "AI-Powered Electrocardiography (ECG) Suite",
    category: "Cardiology Tech",
    description: "Instant 12-lead ECG system embedded with deep neural networks trained on over 2 million ECG records.",
    highlight: "99.4% accuracy in detecting early ischemia & silent flutter",
    specs: ["12-Lead Simultaneous Recording", "Instant Neural Analysis", "Digital EHR Integration"],
    icon: "Cpu",
  },
  {
    id: "tech-4",
    name: "Non-Invasive Arterial Stiffness & ABI Analyzer",
    category: "Vascular Tech",
    description: "Automated pulse wave velocity system measuring arterial age, vascular stiffness, and Ankle-Brachial Index in minutes.",
    highlight: "Accurate vascular age computation vs chronological age",
    specs: ["Multi-cuff Synchronous Measurement", "Pulse Wave Velocity (PWV)", "Automated Vascular Aging Score"],
    icon: "Shield",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    patientName: "Robert Vance",
    age: 58,
    location: "Manhattan, NY",
    treatment: "Executive Health Audit & Cardiology Care",
    rating: 5,
    date: "June 2026",
    quote: "Dr. Reed diagnosed my early arterial blockage before I had a single symptom. Her thoroughness saved my life.",
    story: "During a routine executive health audit, Dr. Reed noticed a subtle abnormality on my 3D Echocardiogram. Further testing revealed an 85% blockage in my left anterior artery. Thanks to her prompt referral and non-invasive intervention, I recovered fully and am back to playing tennis every weekend.",
    verified: true,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200",
  },
  {
    id: "test-2",
    patientName: "Elena Rostova",
    age: 44,
    location: "Brooklyn, NY",
    treatment: "Diabetes Reversal & Thyroid Care",
    rating: 5,
    date: "May 2026",
    quote: "My HbA1c dropped from 8.6 to 5.4 in under 5 months. The personalized care here is unlike any other clinic.",
    story: "I had struggled with uncontrolled diabetes for 7 years. Dr. Reed put me on a Continuous Glucose Monitor and a custom metabolic plan. She listened to me for over an hour during our first visit. I am now completely off insulin injections!",
    verified: true,
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200",
  },
  {
    id: "test-3",
    patientName: "Marcus Thorne",
    age: 62,
    location: "Queens, NY",
    treatment: "Hypertension & Vascular Care",
    rating: 5,
    date: "April 2026",
    quote: "Clean, state-of-the-art facility with zero wait times. Dr. Reed is compassionate and insanely knowledgeable.",
    story: "The clinic environment feels like a 5-star hotel combined with a top-tier university medical center. Scheduling was effortless, the staff is welcoming, and Dr. Reed explained every detail of my Doppler report in plain English.",
    verified: true,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200",
  },
  {
    id: "test-4",
    patientName: "Sarah Jenkins",
    age: 39,
    location: "Staten Island, NY",
    treatment: "Preventive Wellness & Hormone Audit",
    rating: 5,
    date: "March 2026",
    quote: "Finally a doctor who looks at the root cause rather than throwing pills at symptoms!",
    story: "I suffered from chronic fatigue and erratic heart palpitations for months. Dr. Reed conducted a thorough biomarker panel and identified a subclinical thyroid imbalance. Within 4 weeks on her treatment plan, my energy was completely restored.",
    verified: true,
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200",
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "gal-1",
    title: "Executive Consultation Suite",
    category: "facilities",
    imageUrl: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&q=80&w=800",
    description: "Private, comfortable consulting rooms equipped with ambient lighting and high-definition patient education displays.",
  },
  {
    id: "gal-2",
    title: "State-of-the-Art Diagnostic Ultrasound Suite",
    category: "technology",
    imageUrl: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800",
    description: "Our advanced Epiq 7G 3D Echocardiography diagnostic setup for non-invasive heart scans.",
  },
  {
    id: "gal-3",
    title: "Sterile Minor Procedure & Vascular Lounge",
    category: "operating-theater",
    imageUrl: "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=800",
    description: "HEPA-filtered sterile environment for outpatient minor procedures and vascular access.",
  },
  {
    id: "gal-4",
    title: "Modern VIP Patient Reception",
    category: "facilities",
    imageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800",
    description: "Serene, zero-stress waiting lounge with complimentary organic refreshments and high-speed Wi-Fi.",
  },
  {
    id: "gal-5",
    title: "Dr. Evelyn Reed in Consultation",
    category: "doctor",
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=800",
    description: "Dr. Reed discussing diagnostic findings and personalized treatment options with a patient.",
  },
  {
    id: "gal-6",
    title: "In-house Rapid Biomarker Laboratory",
    category: "technology",
    imageUrl: "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&q=80&w=800",
    description: "Fully automated stat lab equipment providing same-day blood chemistry and cardiac marker results.",
  },
];

export const FAQS: FAQItem[] = [
  {
    id: "faq-1",
    category: "Appointments",
    question: "How do I schedule an appointment with Dr. Evelyn Reed?",
    answer: "You can book directly using our online Appointment Booking tool on this website, call our desk at +1 (800) 555-0199, or send us a message via WhatsApp. Our clinic coordinator will confirm your preferred time slot within 2 hours.",
  },
  {
    id: "faq-2",
    category: "Appointments",
    question: "What should I bring to my first consultation?",
    answer: "Please bring a valid photo ID, your active insurance card, a list of current medications or supplements, and any recent lab reports or medical records from the past 12 months.",
  },
  {
    id: "faq-3",
    category: "Insurance & Payment",
    question: "Which insurance plans does AuraHealth accept?",
    answer: "We accept most major commercial PPO & POS plans including BlueCross BlueShield, Aetna, Cigna, UnitedHealthcare, Medicare, and Oxford. For out-of-network patients, we provide itemized superbills for direct insurance reimbursement.",
  },
  {
    id: "faq-4",
    category: "General",
    question: "What makes AuraHealth clinic different from standard clinics?",
    answer: "We offer unhurried 45-to-60 minute physician consultations, direct patient access to state-of-the-art 3D imaging, continuous biomarker tracking, zero long waiting room delays, and a truly integrative medical approach.",
  },
  {
    id: "faq-5",
    category: "Treatments",
    question: "Are the diagnostic tests like 3D Echocardiography painful?",
    answer: "Not at all. 3D Echocardiography and Vascular Doppler scans are 100% painless, non-invasive ultrasound procedures with zero radiation and no downtime.",
  },
  {
    id: "faq-6",
    category: "Appointments",
    question: "What is your cancellation or rescheduling policy?",
    answer: "We request at least 24 hours advance notice for cancellations or rescheduling so we can offer the slot to patients needing priority care. You can easily reschedule via phone or WhatsApp.",
  },
];
